import "./export";
import{B}from "./export";
import*as C from "./export";
import{D}from "./export";
import*as DExports from "./export";
import{E}from "./export";
import*as EExports from "./export";
import{F}from "./export";
import*as FExports from "./export";
import{Z as stuff}from "./export";
import*as Z from "./export";
B();
var num = C.x + C.y;
D();
DExports.foo();
E();
EExports.bar();
F();
var o = new FExports.G();
FExports.G.baz();
stuff();
Z.fun();
