//!! To update the .JS file that generates this declaration file, open the
//!! zipped_js_library.zip file with any archive manager, and modify or update
//!! the contained files.
//!!
//!! This is generated by class_in_zip.js
declare namespace ಠ_ಠ.clutz.class_in_zip {
  class A extends A_Instance {
  }
  class A_Instance {
    private noStructuralTyping_: any;
    constructor (n : number ) ;
    a : number ;
  }
}
declare module 'goog:class_in_zip' {
  import alias = ಠ_ಠ.clutz.class_in_zip;
  export = alias;
}
