//!! To update the .JS file that generates this declaration file, open the
//!! zipped_js_library.zip file with any archive manager, and modify or update
//!! the contained files.
//!!
//!! This is generated by types_in_zip.js
declare namespace ಠ_ಠ.clutz.types_in_zip {
  var bool : boolean ;
  var num : number ;
  var str : string ;
}
declare module 'goog:types_in_zip' {
  import alias = ಠ_ಠ.clutz.types_in_zip;
  export = alias;
}
