//!! To update the .JS file that generates this declaration file, open the
//!! zipped_js_library.zip file with any archive manager, and modify or update
//!! the contained files.
//!!
//!! This is generated by types_in_zip.js
// Generated from src/test/java/com/google/javascript/clutz/testdata/zipped_js_library.zip!/types_in_zip.js
declare namespace ಠ_ಠ.clutz.types_in_zip {
  let bool : boolean ;
  let num : number ;
  let str : string ;
}
declare module 'goog:types_in_zip' {
  import types_in_zip = ಠ_ಠ.clutz.types_in_zip;
  export = types_in_zip;
}
