let x: any;
let y: any;
let v: undefined;
let u: undefined = undefined;
let nil: null = null;
let n: number = 4;
let b: boolean = true;
let s: string = "hello";
let l: number = 6;
const c: number = 8;
